apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.nav.no"
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-min-side-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-proxy/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-proxy/metrics
  replicas:
    min: 2
    max: 4
  secureLogs:
    enabled: true
  ingresses:
    - "https://www.nav.no/tms-min-side-proxy"
  resources:
    limits:
      cpu: "3"
      memory: 1536Mi
    requests:
      cpu: "100m"
      memory: 580Mi
  accessPolicy:
    outbound:
      external:
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: syfomotebehov.prod-fss-pub.nais.io
        - host: min-side-unleash-api.nav.cloud.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
      rules:
        - application: tms-utkast
        - application: dittnav-event-aggregator
        - application: tms-statistikk
        - application: tms-personalia-api
        - application: tms-mikrofrontend-selector
        - application: tms-varsel-api
        - application: meldekort-api
          namespace: meldekort
        - application: soknad-api
          namespace: aap
        - application: isdialogmote
          namespace: teamsykefravr
        - application: veilarboppfolging
          namespace: pto
          cluster: prod-fss
        - application: aia-backend
          namespace: paw
          cluster: prod-gcp
  env:
    - name: STATISTIKK_BASE_URL
      value: http://tms-statistikk
    - name: STATISTIKK_CLIENT_ID
      value: prod-gcp.min-side.tms-statistikk
    - name: AAP_BASE_URL
      value: http://soknad-api.aap
    - name: AAP_CLIENT_ID
      value: prod-gcp:aap:soknad-api
    - name: CORS_ALLOWED_ORIGINS
      value: www.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: MELDEKORT_BASE_URL
      value: http://meldekort-api.meldekort/meldekort/meldekort-api
    - name: MELDEKORT_CLIENT_ID
      value: prod-gcp:meldekort:meldekort-api
    - name: PERSONALIA_BASE_URL
      value: http://tms-personalia-api/tms-personalia-api
    - name: PERSONALIA_CLIENT_ID
      value: prod-gcp:min-side:tms-personalia-api
    - name: SELCTOR_BASE_URL
      value: http://tms-mikrofrontend-selector
    - name: SELCTOR_CLIENT_ID
      value: prod-gcp:min-side:tms-mikrofrontend-selector
    - name: UTKAST_BASE_URL
      value: http://tms-utkast
    - name: UTKAST_CLIENT_ID
      value: prod-gcp:min-side:tms-utkast
    - name: SYK_DIALOGMOTE_BASE_URL
      value: http://isdialogmote.teamsykefravr
    - name: SYK_DIALOGMOTE_CLIENT_ID
      value: prod-gcp:teamsykefravr:isdialogmote
    - name: OPPFOLGING_API_URL
      value: https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging
    - name: OPPFOLGING_CLIENT_ID
      value: prod-fss:pto:veilarboppfolging
    - name: AIA_API_URL
      value: http://aia-backend.paw
    - name: AIA_CLIENT_ID
      value: prod-gcp:paw:aia-backend
    - name: SYFO_MOTEBEHOV_URL
      value: https://syfomotebehov.prod-fss-pub.nais.io
    - name: SYFO_MOTEBEHOV_CLIENT_ID
      value: prod-fss:team-esyfo:syfomotebehov
    - name: UNLEASH_ENVIRONMENT
      value: production
    - name: PDL_API_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_API_CLIENT_ID
      value: "prod-fss:pdl:pdl-api"
    - name: PDL_BEHANDLINGSNUMMER
      value: "B328"
  envFrom:
    - secret: tms-min-side-proxy-unleash-api-token

---
apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tms-min-side-proxy
  namespace: min-side
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: min-side
  secretName: tms-min-side-proxy-unleash-api-token
  environment: production
